### ISSUE TITLE
Object.keys(pages).forEach……………template少了一个+号

### ISSUE THREAD

**Issue by zhangfu-git** [jincui/webpack-multiplepage#1]

**Comment by zhangfu-git** [comment]
Object.keys(pages).forEach(function(pageName){
   plugins.push(
     new HtmlWebpackPlugin({
         template: './source/pages/'+ pageName+ '/' + pageName + '.jade',
         filename: pageName +'.html',
         chunks: [ 'vendor', pageName],
     })
   );
});

chunks:   是否要改为common才对？？

**Comment by jincui** [comment]
thanks, fix it

**Comment by jincui** [comment]
@zhangfu-git  thanks, fix it
